In [3]:
#numpy have two array 
# single dimensional array

import numpy as np
n1=np.array([1,2,4,5,6])
n1

array([1, 2, 4, 5, 6])

In [4]:
 # multidimensional array
import numpy as np
n2=np.array([[1,3,5,6],[1,2,8,9]])
n2

array([[1, 3, 5, 6],
       [1, 2, 8, 9]])

In [7]:
import numpy as np 
n1=np.zeros([2,3])
n1

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
import numpy as np 
n1=np.full([2,3],10)
n1

array([[10, 10, 10],
       [10, 10, 10]])

In [10]:
import numpy as np 
n1=np.arange(2,10)
n1

array([2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
import numpy as np 
n1=np.arange(2,10,2)
n1

array([2, 4, 6, 8])

In [12]:
import numpy as np 
n1=np.arange(2,50,5)
n1

array([ 2,  7, 12, 17, 22, 27, 32, 37, 42, 47])

In [13]:
import numpy as np 
n1=np.arange(5,55,5)
n1

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [14]:
import numpy as np 
n1=np.random.randint(1,100,5)
n1

array([27, 96, 61, 39, 98])

In [15]:
import numpy as np 
n1=np.random.randint(1,100,10)
n1

array([67, 71, 73, 83, 29, 41, 86, 82, 50, 41])

In [16]:
# shape
import numpy as np 
n1=np.array([1,3,54,6])
n1.shape

(4,)

In [17]:
# shape
import numpy as np 
n1=np.array([[1,3,54,6],[3,4,5,7]])
n1.shape

(2, 4)

In [18]:
n1.shape=(4,2)
n1

array([[ 1,  3],
       [54,  6],
       [ 3,  4],
       [ 5,  7]])

In [20]:

n1.shape=(4,2)
n1

array([[ 1,  3],
       [54,  6],
       [ 3,  4],
       [ 5,  7]])

In [21]:
# stack
# horizontal stack , vertical stack and column_stack
# it is use for adding array
import numpy as np
n1=np.array([2,3,4,5])
n2=np.array([4,5,6,7])
np.vstack([n1,n2])

array([[2, 3, 4, 5],
       [4, 5, 6, 7]])

In [22]:
# horizontal array
np.hstack([n1,n2])

array([2, 3, 4, 5, 4, 5, 6, 7])

In [23]:
np.column_stack([n1,n2])

array([[2, 4],
       [3, 5],
       [4, 6],
       [5, 7]])

In [25]:
# using of intersection and setdifference
import numpy as np
n1=np.array([2,3,4,5])
n2=np.array([4,5,6,7])
np.intersect1d(n1,n2)

array([4, 5])

In [26]:
np.intersect1d(n2,n1)

array([4, 5])

In [31]:
np.setdiff1d(n1,n2)

array([2, 3])

In [34]:
import numpy as np
n1=np.array([1,4,6,7,8,9])
np.mean(n1)

5.833333333333333

In [36]:
np.median(n1)

6.5

In [37]:
np.std(n1)

2.6718699236468995

In [38]:
import numpy as np
n1=np.array([1,4,6,7,8,9])
n1*4

array([ 4, 16, 24, 28, 32, 36])

In [39]:
n1-2

array([-1,  2,  4,  5,  6,  7])

In [40]:
n1+6

array([ 7, 10, 12, 13, 14, 15])

In [41]:
n1

array([0.14285714, 0.57142857, 0.85714286, 1.        , 1.14285714,
       1.28571429])

In [43]:
import numpy as np
n1=np.array([2,3,4,5])
n2=np.array([2,3,4,6])
np.sum([n1,n1])

28

In [44]:
np.sum([n1,n1],axis=0)

array([ 4,  6,  8, 10])

In [45]:
np.sum([n1,n1],axis=1)

array([14, 14])

In [46]:
# from here we are starting pandas 
# pandas stands for panel data and it is the core branch of data manipulation and data analysis
# there are two types of pandas
# one dimensional and multidimensional 
# one-dimensional 



In [48]:
import pandas as pd
n1=pd.Series([2,5,7,8])
n1

0    2
1    5
2    7
3    8
dtype: int64

In [49]:
# with index attributes
n1=pd.Series([2,5,67,8],index=['a','b','c','d'])
n1

a     2
b     5
c    67
d     8
dtype: int64

In [54]:
n1=pd.Series([2,5,67,8],index=['sanjay','manay','chandan','dipak'])
n1

sanjay      2
manay       5
chandan    67
dipak       8
dtype: int64

In [55]:
# by using the dictionary
import pandas as pd
n2=pd.Series({'sanjay':22,'ajay':44,'manjay':66})
n2

sanjay    22
ajay      44
manjay    66
dtype: int64

In [56]:
# by using the dictionary with attributes
import pandas as pd
n2=pd.Series({'sanjay':22,'ajay':44,'manjay':66},index=['a','b','sanjay','manjay'])
n2

a          NaN
b          NaN
sanjay    22.0
manjay    66.0
dtype: float64

In [57]:
import pandas as pd
n1=pd.Series([1,4,5,7,8,9])
n1*6

0     6
1    24
2    30
3    42
4    48
5    54
dtype: int64

In [58]:
n1-5

0   -4
1   -1
2    0
3    2
4    3
5    4
dtype: int64

In [59]:
n1/8

0    0.125
1    0.500
2    0.625
3    0.875
4    1.000
5    1.125
dtype: float64

In [60]:
n1[4]

8

In [63]:
n1[:-3]

0    1
1    4
2    5
dtype: int64

In [65]:
# multi-dimensional pandas
import pandas as pd
n1=pd.DataFrame({"Name":['sanjay','ajay','manjay','ranjay'],"Mark":[2,4,5,8]})
n1

Name  Mark
0  sanjay     2
1    ajay     4
2  manjay     5
3  ranjay     8

In [72]:
import pandas as pd
n2=pd.DataFrame({"Student's name":['radhe','ajay','sanjay','dipak'],"Marks":[33,66,77,88]})
n2

Student's name  Marks
0          radhe     33
1           ajay     66
2         sanjay     77
3          dipak     88

In [73]:

import pandas as pd
n2=pd.DataFrame({"Student's name":['radhe','ajay','sanjay','dipak','sita','gita'],"Marks":[33,66,77,88,99,77]})
n2


Student's name  Marks
0          radhe     33
1           ajay     66
2         sanjay     77
3          dipak     88
4           sita     99
5           gita     77

In [74]:
n2.head()

Student's name  Marks
0          radhe     33
1           ajay     66
2         sanjay     77
3          dipak     88
4           sita     99

In [75]:
n2.tail()

Student's name  Marks
1           ajay     66
2         sanjay     77
3          dipak     88
4           sita     99
5           gita     77

In [78]:
n1.describe()

Mark
count  4.00
mean   4.75
std    2.50
min    2.00
25%    3.50
50%    4.50
75%    5.75
max    8.00

In [79]:
n2.describe()

Marks
count   6.000000
mean   73.333333
std    22.721502
min    33.000000
25%    68.750000
50%    77.000000
75%    85.250000
max    99.000000

In [80]:
n2

Student's name  Marks
0          radhe     33
1           ajay     66
2         sanjay     77
3          dipak     88
4           sita     99
5           gita     77

In [81]:
n2.drop([1,2],axis=0)

Student's name  Marks
0          radhe     33
3          dipak     88
4           sita     99
5           gita     77

In [82]:
n2.drop('Marks',axis=1)

Student's name
0          radhe
1           ajay
2         sanjay
3          dipak
4           sita
5           gita

In [83]:
n2

Student's name  Marks
0          radhe     33
1           ajay     66
2         sanjay     77
3          dipak     88
4           sita     99
5           gita     77

In [89]:
n2.max()

Student's name    sita
Marks               99
dtype: object

In [90]:
n2.min()

Student's name    ajay
Marks               33
dtype: object